apiVersion: v1
kind: Service
metadata:
   name: springboot-k8s-azure-svc
spec:
    selector:
      app: springboot-k8s-azure
    ports:
      - protocol: "TCP"
        port: 8080
        targetPort: 8080
    type: NodePort       